repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10 # Check Ruff's releases for the latest stable version: https://github.com/astral-sh/ruff-pre-commit/releases
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix] 
      - id: ruff-format